package com.relic.deserializer.response

private const val SUB = "{\"kind\": \"t5\", \"data\": {\"user_flair_background_color\": null, \"submit_text_html\": null, \"restrict_posting\": true, \"user_is_banned\": false, \"free_form_reports\": true, \"wiki_enabled\": true, \"user_is_muted\": false, \"user_can_flair_in_sr\": null, \"display_name\": \"BoiledBuns\", \"header_img\": null, \"title\": \"BoiledBuns\", \"icon_size\": null, \"primary_color\": \"\", \"active_user_count\": null, \"icon_img\": \"\", \"display_name_prefixed\": \"r/BoiledBuns\", \"accounts_active\": null, \"public_traffic\": false, \"subscribers\": 1, \"user_flair_richtext\": [], \"name\": \"t5_12jodh\", \"quarantine\": false, \"hide_ads\": false, \"emojis_enabled\": false, \"advertiser_category\": \"\", \"public_description\": \"Relic Testing\", \"comment_score_hide_mins\": 0, \"user_has_favorited\": false, \"user_flair_template_id\": null, \"community_icon\": \"\", \"banner_background_image\": \"\", \"original_content_tag_enabled\": false, \"submit_text\": \"\", \"description_html\": \"test description\", \"spoilers_enabled\": true, \"header_title\": \"\", \"header_size\": null, \"user_flair_position\": \"right\", \"all_original_content\": false, \"collections_enabled\": true, \"is_enrolled_in_new_modmail\": true, \"key_color\": \"\", \"event_posts_enabled\": true, \"can_assign_user_flair\": false, \"created\": 1559706557.0, \"wls\": null, \"show_media_preview\": true, \"submission_type\": \"any\", \"user_is_subscriber\": true, \"disable_contributor_requests\": false, \"allow_videogifs\": true, \"user_flair_type\": \"text\", \"collapse_deleted_comments\": false, \"emojis_custom_size\": null, \"public_description_html\": \"test description\", \"allow_videos\": false, \"notification_level\": \"low\", \"can_assign_link_flair\": false, \"has_menu_widget\": false, \"accounts_active_is_fuzzed\": false, \"submit_text_label\": \"\", \"link_flair_position\": \"\", \"user_sr_flair_enabled\": null, \"user_flair_enabled_in_sr\": false, \"allow_discovery\": true, \"user_sr_theme_enabled\": true, \"link_flair_enabled\": false, \"subreddit_type\": \"private\", \"suggested_comment_sort\": null, \"banner_img\": \"\", \"user_flair_text\": null, \"banner_background_color\": \"\", \"show_media\": true, \"id\": \"12jodh\", \"user_is_moderator\": true, \"over18\": false, \"description\": \"Relic Testing\", \"submit_link_label\": \"\", \"user_flair_text_color\": null, \"restrict_commenting\": false, \"user_flair_css_class\": null, \"allow_images\": true, \"lang\": \"en\", \"whitelist_status\": null, \"url\": \"/r/BoiledBuns/\", \"created_utc\": 1559677757.0, \"banner_size\": null, \"mobile_banner_image\": \"\", \"user_is_contributor\": true}}"

const val SUB_RESPONSE = SUB

const val SUBS_RESPONSE = "{\"kind\": \"Listing\", \"data\": {\"modhash\": null, \"dist\": 1, \"children\": [$SUB_RESPONSE], \"after\": \"t5_2qhae\", \"before\": null}}"

const val SUB_PREVIEW = "{\"active_user_count\": 4519, \"icon_img\": \"https://b.thumbs.redditmedia.com/kOJ2mLk2e2e2kOto6K188zsLQzJE6Yv3AMi3Pv6kwkM.png\", \"key_color\": \"#7e53c1\", \"name\": \"hearthstone\", \"subscriber_count\": 1044162, \"allow_images\": true}"

const val SUB_SEARCH_RESPONSE = "{\"subreddits\": [$SUB_PREVIEW]}"